-- =============================================================================
-- Database Population Script for wcall-rds-postgresql-17
-- Run this after Terraform provisioning via psql
-- =============================================================================

-- Create application schema
CREATE SCHEMA IF NOT EXISTS wcall;

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS wcall.company (
    companyid   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    companyname varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS wcall.product (
    productid   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    productname varchar(100) NOT NULL,
    companyid   int REFERENCES wcall.company(companyid)
);

-- -----------------------------------------------------------------------------
-- Sample Data
-- -----------------------------------------------------------------------------

INSERT INTO wcall.company (companyname) VALUES
    ('Grafana Labs'),
    ('Azure'),
    ('Amazon'),
    ('Google');

INSERT INTO wcall.product (productname, companyid) VALUES
    ('Grafana Cloud',    1),
    ('Grafana OnPrem',   1),
    ('Azure Monitor',    2),
    ('AWS CloudWatch',   3),
    ('Google Cloud Ops', 4);

-- -----------------------------------------------------------------------------
-- Verify
-- -----------------------------------------------------------------------------

SELECT c.companyname, p.productname
FROM wcall.company c
JOIN wcall.product p ON c.companyid = p.companyid
ORDER BY c.companyname;
