-- Runs on first database initialization as POSTGRES_USER (superuser)
-- Default connection: super_awesome_application

-- Enable pg_stat_statements for query monitoring
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS pg_buffercache;

-- Create application schema and sample data
CREATE SCHEMA IF NOT EXISTS wcall;

CREATE TABLE IF NOT EXISTS wcall.company (
    companyid   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    companyname varchar(50) NOT NULL
);

INSERT INTO wcall.company (companyname) VALUES
    ('Grafana Labs'),
    ('Azure'),
    ('Amazon'),
    ('Google');

-- Switch to postgres for system-level setup
\connect postgres

CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- Create db-o11y monitoring user
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'db-o11y') THEN
        CREATE USER "db-o11y" WITH PASSWORD 'db-o11y-postgres';
    END IF;
END
$$;

GRANT pg_monitor TO "db-o11y";
GRANT pg_read_all_stats TO "db-o11y";
GRANT pg_read_all_data TO "db-o11y";

-- Exclude the monitoring user's own queries from pg_stat_statements
ALTER ROLE "db-o11y" SET pg_stat_statements.track = 'none';

-- Grant schema permissions back in super_awesome_application
\connect super_awesome_application

GRANT USAGE ON SCHEMA public TO "db-o11y";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "db-o11y";
GRANT USAGE ON SCHEMA wcall TO "db-o11y";
GRANT SELECT ON ALL TABLES IN SCHEMA wcall TO "db-o11y";

-- Create wcall application role
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'wcall') THEN
        CREATE USER wcall WITH PASSWORD 'wcall';
    END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO wcall;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO wcall;
GRANT USAGE ON SCHEMA wcall TO wcall;
GRANT SELECT ON ALL TABLES IN SCHEMA wcall TO wcall;
-- Track all queries made by the wcall role from pg_stat_statements
ALTER USER "wcall" SET pg_stat_statements.track = 'all';
